//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Data;



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IService1", CallbackContract=typeof(IService1Callback))]
public interface IService1
{
    
    // CODEGEN: Parameter 'GetDataResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    GetDataResponse GetData(GetDataRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
    System.Threading.Tasks.Task<GetDataResponse> GetDataAsync(GetDataRequest request);
    
    // CODEGEN: Parameter 'GetDataUsingDataContractResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    GetDataUsingDataContractResponse GetDataUsingDataContract(GetDataUsingDataContractRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
    System.Threading.Tasks.Task<GetDataUsingDataContractResponse> GetDataUsingDataContractAsync(GetDataUsingDataContractRequest request);
    
    // CODEGEN: Parameter 'name' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
    [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IService1/CreateTable")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    void CreateTable(CreateTable request);
    
    [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IService1/CreateTable")]
    System.Threading.Tasks.Task CreateTableAsync(CreateTable request);
    
    // CODEGEN: Parameter 'name' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteTable", ReplyAction="http://tempuri.org/IService1/DeleteTableResponse")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    DeleteTableResponse DeleteTable(DeleteTableRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteTable", ReplyAction="http://tempuri.org/IService1/DeleteTableResponse")]
    System.Threading.Tasks.Task<DeleteTableResponse> DeleteTableAsync(DeleteTableRequest request);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IService1Callback
{
    
    // CODEGEN: Parameter 'database' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
    [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IService1/OnDatabaseUpdated")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    void OnDatabaseUpdated(OnDatabaseUpdated request);
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="GetData", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
public partial class GetDataRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
    public int value;
    
    public GetDataRequest()
    {
    }
    
    public GetDataRequest(int value)
    {
        this.value = value;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="GetDataResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
public partial class GetDataResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string GetDataResult;
    
    public GetDataResponse()
    {
    }
    
    public GetDataResponse(string GetDataResult)
    {
        this.GetDataResult = GetDataResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="GetDataUsingDataContract", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
public partial class GetDataUsingDataContractRequest
{
    
    public GetDataUsingDataContractRequest()
    {
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="GetDataUsingDataContractResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
public partial class GetDataUsingDataContractResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Data.DataTable GetDataUsingDataContractResult;
    
    public GetDataUsingDataContractResponse()
    {
    }
    
    public GetDataUsingDataContractResponse(System.Data.DataTable GetDataUsingDataContractResult)
    {
        this.GetDataUsingDataContractResult = GetDataUsingDataContractResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="CreateTable", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
public partial class CreateTable
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string name;
    
    public CreateTable()
    {
    }
    
    public CreateTable(string name)
    {
        this.name = name;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="DeleteTable", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
public partial class DeleteTableRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string name;
    
    public DeleteTableRequest()
    {
    }
    
    public DeleteTableRequest(string name)
    {
        this.name = name;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="DeleteTableResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
public partial class DeleteTableResponse
{
    
    public DeleteTableResponse()
    {
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/WcfServiceLibrary")]
public partial class CompositeType
{
    
    private System.Data.DataTable boolValueField;
    
    private string stringValueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
    public System.Data.DataTable BoolValue
    {
        get
        {
            return this.boolValueField;
        }
        set
        {
            this.boolValueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
    public string StringValue
    {
        get
        {
            return this.stringValueField;
        }
        set
        {
            this.stringValueField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="OnDatabaseUpdated", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
public partial class OnDatabaseUpdated
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public CompositeType database;
    
    public OnDatabaseUpdated()
    {
    }
    
    public OnDatabaseUpdated(CompositeType database)
    {
        this.database = database;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IService1Channel : IService1, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class Service1Client : System.ServiceModel.DuplexClientBase<IService1>, IService1
{
    
    public Service1Client(System.ServiceModel.InstanceContext callbackInstance) : 
            base(callbackInstance)
    {
    }
    
    public Service1Client(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
            base(callbackInstance, endpointConfigurationName)
    {
    }
    
    public Service1Client(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
            base(callbackInstance, endpointConfigurationName, remoteAddress)
    {
    }
    
    public Service1Client(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(callbackInstance, endpointConfigurationName, remoteAddress)
    {
    }
    
    public Service1Client(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(callbackInstance, binding, remoteAddress)
    {
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    GetDataResponse IService1.GetData(GetDataRequest request)
    {
        return base.Channel.GetData(request);
    }
    
    public string GetData(int value)
    {
        GetDataRequest inValue = new GetDataRequest();
        inValue.value = value;
        GetDataResponse retVal = ((IService1)(this)).GetData(inValue);
        return retVal.GetDataResult;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<GetDataResponse> IService1.GetDataAsync(GetDataRequest request)
    {
        return base.Channel.GetDataAsync(request);
    }
    
    public System.Threading.Tasks.Task<GetDataResponse> GetDataAsync(int value)
    {
        GetDataRequest inValue = new GetDataRequest();
        inValue.value = value;
        return ((IService1)(this)).GetDataAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    GetDataUsingDataContractResponse IService1.GetDataUsingDataContract(GetDataUsingDataContractRequest request)
    {
        return base.Channel.GetDataUsingDataContract(request);
    }
    
    public System.Data.DataTable GetDataUsingDataContract()
    {
        GetDataUsingDataContractRequest inValue = new GetDataUsingDataContractRequest();
        GetDataUsingDataContractResponse retVal = ((IService1)(this)).GetDataUsingDataContract(inValue);
        return retVal.GetDataUsingDataContractResult;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<GetDataUsingDataContractResponse> IService1.GetDataUsingDataContractAsync(GetDataUsingDataContractRequest request)
    {
        return base.Channel.GetDataUsingDataContractAsync(request);
    }
    
    public System.Threading.Tasks.Task<GetDataUsingDataContractResponse> GetDataUsingDataContractAsync()
    {
        GetDataUsingDataContractRequest inValue = new GetDataUsingDataContractRequest();
        return ((IService1)(this)).GetDataUsingDataContractAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    void IService1.CreateTable(CreateTable request)
    {
        base.Channel.CreateTable(request);
    }
    
    public void CreateTable(string name)
    {
        CreateTable inValue = new CreateTable();
        inValue.name = name;
        ((IService1)(this)).CreateTable(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task IService1.CreateTableAsync(CreateTable request)
    {
        return base.Channel.CreateTableAsync(request);
    }
    
    public System.Threading.Tasks.Task CreateTableAsync(string name)
    {
        CreateTable inValue = new CreateTable();
        inValue.name = name;
        return ((IService1)(this)).CreateTableAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    DeleteTableResponse IService1.DeleteTable(DeleteTableRequest request)
    {
        return base.Channel.DeleteTable(request);
    }
    
    public void DeleteTable(string name)
    {
        DeleteTableRequest inValue = new DeleteTableRequest();
        inValue.name = name;
        DeleteTableResponse retVal = ((IService1)(this)).DeleteTable(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<DeleteTableResponse> IService1.DeleteTableAsync(DeleteTableRequest request)
    {
        return base.Channel.DeleteTableAsync(request);
    }
    
    public System.Threading.Tasks.Task<DeleteTableResponse> DeleteTableAsync(string name)
    {
        DeleteTableRequest inValue = new DeleteTableRequest();
        inValue.name = name;
        return ((IService1)(this)).DeleteTableAsync(inValue);
    }
}
