//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Data;



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IService1")]
public interface IService1
{
    
    // CODEGEN: Parameter 'GetDataResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    GetDataResponse GetData(GetDataRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
    System.Threading.Tasks.Task<GetDataResponse> GetDataAsync(GetDataRequest request);
    
    // CODEGEN: Parameter 'GetDataUsingDataContractResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    GetDataUsingDataContractResponse GetDataUsingDataContract(GetDataUsingDataContractRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
    System.Threading.Tasks.Task<GetDataUsingDataContractResponse> GetDataUsingDataContractAsync(GetDataUsingDataContractRequest request);
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="GetData", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
public partial class GetDataRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
    public int value;
    
    public GetDataRequest()
    {
    }
    
    public GetDataRequest(int value)
    {
        this.value = value;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="GetDataResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
public partial class GetDataResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string GetDataResult;
    
    public GetDataResponse()
    {
    }
    
    public GetDataResponse(string GetDataResult)
    {
        this.GetDataResult = GetDataResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="GetDataUsingDataContract", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
public partial class GetDataUsingDataContractRequest
{
    
    public GetDataUsingDataContractRequest()
    {
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="GetDataUsingDataContractResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
public partial class GetDataUsingDataContractResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Data.DataTable GetDataUsingDataContractResult;
    
    public GetDataUsingDataContractResponse()
    {
    }
    
    public GetDataUsingDataContractResponse(System.Data.DataTable GetDataUsingDataContractResult)
    {
        this.GetDataUsingDataContractResult = GetDataUsingDataContractResult;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IService1Channel : IService1, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class Service1Client : System.ServiceModel.ClientBase<IService1>, IService1
{
    
    public Service1Client()
    {
    }
    
    public Service1Client(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public Service1Client(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    GetDataResponse IService1.GetData(GetDataRequest request)
    {
        return base.Channel.GetData(request);
    }
    
    public string GetData(int value)
    {
        GetDataRequest inValue = new GetDataRequest();
        inValue.value = value;
        GetDataResponse retVal = ((IService1)(this)).GetData(inValue);
        return retVal.GetDataResult;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<GetDataResponse> IService1.GetDataAsync(GetDataRequest request)
    {
        return base.Channel.GetDataAsync(request);
    }
    
    public System.Threading.Tasks.Task<GetDataResponse> GetDataAsync(int value)
    {
        GetDataRequest inValue = new GetDataRequest();
        inValue.value = value;
        return ((IService1)(this)).GetDataAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    GetDataUsingDataContractResponse IService1.GetDataUsingDataContract(GetDataUsingDataContractRequest request)
    {
        return base.Channel.GetDataUsingDataContract(request);
    }
    
    public System.Data.DataTable GetDataUsingDataContract()
    {
        GetDataUsingDataContractRequest inValue = new GetDataUsingDataContractRequest();
        GetDataUsingDataContractResponse retVal = ((IService1)(this)).GetDataUsingDataContract(inValue);
        return retVal.GetDataUsingDataContractResult;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<GetDataUsingDataContractResponse> IService1.GetDataUsingDataContractAsync(GetDataUsingDataContractRequest request)
    {
        return base.Channel.GetDataUsingDataContractAsync(request);
    }
    
    public System.Threading.Tasks.Task<GetDataUsingDataContractResponse> GetDataUsingDataContractAsync()
    {
        GetDataUsingDataContractRequest inValue = new GetDataUsingDataContractRequest();
        return ((IService1)(this)).GetDataUsingDataContractAsync(inValue);
    }
}
